### ISSUE TITLE
win11运行报错

### ISSUE THREAD

**Issue by sqrta** [nyaoouo/GBFR-ACT#31]
我在win11下使用python11运行 python act_ws.py 会报错。

Traceback (most recent call last):
  File "D:\mods\GBF\GBFR-ACT\injector.py", line 1591, in get_python_base
    return self.get_ldr_data(PYTHON_DLL).DllBase
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mods\GBF\GBFR-ACT\injector.py", line 1468, in get_ldr_data
    raise KeyError(f'dll {dll_name!r} not found')
KeyError: "dll 'python311.dll' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\mods\GBF\GBFR-ACT\act_ws.py", line 773, in <module>
    main()
  File "D:\mods\GBF\GBFR-ACT\act_ws.py", line 764, in main
    process.injector.wait_inject()
  File "D:\mods\GBF\GBFR-ACT\injector.py", line 1255, in wait_inject
    self.logger.debug(f"python base {self.process.get_python_base(True):#x}")
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mods\GBF\GBFR-ACT\injector.py", line 1594, in get_python_base
    base = self.load_library(Process.current.get_ldr_data(PYTHON_DLL).FullDllName.value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mods\GBF\GBFR-ACT\injector.py", line 1521, in load_library
    if err := self.read_u32(result_at): raise ctypes.WinError(err)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied.

安装pywin32也不能解决

**Comment by nyaoouo** [comment]
确保使用正确的python版本，别用conda或者winstore安装的，从官网下python管理员安装，关掉防毒之类
