### ISSUE TITLE
Win11无法启动

### ISSUE THREAD

**Issue by MissHyacinth** [nyaoouo/GBFR-ACT#54]
Traceback (most recent call last):
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\act_ws.py", line 775, in <module>
    main()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\act_ws.py", line 756, in main
    run_admin()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1733, in run_admin
    raise PermissionError("Need admin permission, a new process should be started, if not, please run it as admin manually")
PermissionError: Need admin permission, a new process should be started, if not, please run it as admin manually
Press any key to continue . . .
以上是运行act_ws的文本，弹出新窗口后显示
Traceback (most recent call last):
  File "C:\Users\16349\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\16349\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1247, in start_server
    self.process.exec_shell_code(shell_code, auto_inject=True)
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1609, in exec_shell_code
    res = self.call(py_base + self._get_pyfunc_offset("PyRun_String"), f'with open({f.name!r},encoding="utf-8") as f:exec(f.read())'.encode('utf-8'), 0x101, p_dict, p_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1547, in call
    with self.name_space() as name_space:
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1149, in __exit__
    self.free()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1143, in free
    self.process.free(*self.res.pop())
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1294, in free
    return kernel32.VirtualFreeEx(self.handle, address, size, 0x4000)  # MEM_DECOMMIT
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 40, in wrapper
    raise ctypes.WinError()
PermissionError: [WinError 5] 拒绝访问。
Traceback (most recent call last):
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\act_ws.py", line 775, in <module>
    main()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\act_ws.py", line 766, in main
    process.injector.wait_inject()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1259, in wait_inject
    wait_until(self.is_active, timeout=10)
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1096, in wait_until
    raise TimeoutError
TimeoutError

如运行uac_start,则显示

Python: can't open file 'D:\\Application\\GBFR-ACT-master\\GBFR-ACT-master\\3.12.2': [Errno 2] No such file or directory
Python: can't open file 'D:\\Application\\GBFR-ACT-master\\GBFR-ACT-master\\3.11.8': [Errno 2] No such file or directory
Found Python 3.11 64-bit at C:\Users\16349\AppData\Local\Microsoft\WindowsApps\python.exe
Traceback (most recent call last):
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1591, in get_python_base
    return self.get_ldr_data(PYTHON_DLL).DllBase
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1468, in get_ldr_data
    raise KeyError(f'dll {dll_name!r} not found')
KeyError: "dll 'python311.dll' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\act_ws.py", line 775, in <module>
    main()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\act_ws.py", line 766, in main
    process.injector.wait_inject()
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1255, in wait_inject
    self.logger.debug(f"python base {self.process.get_python_base(True):#x}")
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1594, in get_python_base
    base = self.load_library(Process.current.get_ldr_data(PYTHON_DLL).FullDllName.value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Application\GBFR-ACT-master\GBFR-ACT-master\injector.py", line 1521, in load_library
    if err := self.read_u32(result_at): raise ctypes.WinError(err)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 拒绝访问。

从python官网安装了64位的3.12，后续又安装了py32，但是仍然无法解决。
右键菜单里已经给了文件完全权限，python安装到路径并且是管理员安装的，uac_start文件使用管理员权限运行

操作系统版本win11家庭版 22H2 22621.3155

**Comment by T-kON99** [comment]
Pretty sure the script only checks for python 3.11 and not 3.12, can you try with python 3.11.x?

**Comment by Emptiest** [comment]
I can confirm I tried using Python 3.12 and the script does not work with it.
