### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by I-ing** [nyaoouo/GBFR-ACT#69]
系统Windows 10 专业版 22H2 python是官网下载的3.11.6 运行act_ws.py和uac_start.cmd都会出现如下错误
Exception in thread Thread-2 (start_server):
Traceback (most recent call last):
  File "C:\Users\Iingj\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Iingj\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "E:\GBFR-ACT-master\injector.py", line 1247, in start_server
    self.process.exec_shell_code(shell_code, auto_inject=True)
  File "E:\GBFR-ACT-master\injector.py", line 1628, in exec_shell_code
    raise RuntimeError(f"Exception in shell: {type_name}: {desc}")
RuntimeError: Exception in shell: SyntaxError: ("(unicode error) 'utf-8' codec can't decode byte 0x89 in position 2: invalid start byte", ('<string>', 1, 87, 'with open(\'C:\\\\Windows\\\\Temp\\\\tmpc7l6epwq\',encoding="utf-8") as f:exec(f.read())UH��H��(SH1�H�\x10\n', 1, -1))

Traceback (most recent call last):
  File "E:\GBFR-ACT-master\act_ws.py", line 781, in <module>
    main()
  File "E:\GBFR-ACT-master\act_ws.py", line 772, in main
    process.injector.wait_inject()
  File "E:\GBFR-ACT-master\injector.py", line 1259, in wait_inject
    wait_until(self.is_active, timeout=10)
  File "E:\GBFR-ACT-master\injector.py", line 1096, in wait_until
    raise TimeoutError
TimeoutError
问下是什么问题？有解决办法吗？

**Comment by nyaoouo** [comment]
重启试试

**Comment by I-ing** [comment]
重启过了 游戏、脚本、电脑都重启了 还是一样的问题

**Comment by a369119** [comment]
我也是遇到同樣問題 跟上面完全一樣的描述
